---
- name: Ensure the key is present
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
- name: Add repository
  apt_repository:
    repo: 'deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx'
    state: present
  notify:
  - Update apt
- name: Ensure nginx is at the latest version
  apt:
    pkg: nginx
    state: latest
- name: Ensure logrotate is at the latest version
  apt:
    pkg: logrotate
    state: latest
- name: Ensure the log archive folder is here
  file:
    path: /var/log/nginx/archive
    state: directory
- name: Rotate logs and archive
  lineinfile:
    dest: /etc/logrotate.d/nginx
    state: present
    line: '        olddir /var/log/nginx/archive'
    insertafter: '        sharedscripts'
- name: Ensure the enabled folder is here
  file:
    path: /etc/nginx/enabled
    state: directory
- name: Ensure the available folder is here
  file:
    path: /etc/nginx/available
    state: directory
- name: Removes the conf.d directory
  file:
    path: /etc/nginx/conf.d
    state: absent
- name: Writes the default confs
  copy:
    src: default.hhvm.conf
    dest: /etc/nginx/available/default.hhvm.conf
- name: Writes the default confs
  copy:
    src: default.php-fpm.conf
    dest: /etc/nginx/available/default.php-fpm.conf
- name: Writes the default confs
  copy:
    src: default.ghost.conf
    dest: /etc/nginx/available/default.ghost.conf
- name: Writes the secured version of the configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
  - Restart Nginx
- name: Writes the php-fpm standard configuration
  copy:
    src: php-fpm.conf
    dest: /etc/nginx/php-fpm.conf
- name: Writes the favicon/robots configuration
  copy:
    src: favicon.robots.conf
    dest: /etc/nginx/favicon.robots.conf
  notify:
  - Restart Nginx
- name: Create nginx htpasswd
  htpasswd:
    path: /etc/nginx/available/.htpasswd
    name: "{{ user }}"
    password: "{{ htpasswd }}"
    owner: root
    group: www-data
    mode: 0640
- name: Writes the ssl configuration
  copy:
    src: ssl.conf
    dest: /etc/nginx/ssl.conf
  notify:
  - Restart Nginx
- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes

