---
- name: Add correct /etc/apt/sources.list file
  copy:
    src: "sources.{{ ansible_distribution_release }}.list"
    dest: "/etc/apt/sources.list"
    owner: root
- name: Ensure aptitude is installed
  apt:
    pkg: aptitude
    state: latest
- name: Update apt
  apt: update_cache=yes
- name: Upgrade apt
  apt: upgrade=full
- name: Ensure sudo is installed
  apt:
    pkg: sudo
    state: latest
- name: "Add user to sudo group"
  user:
    name: "{{user}}"
    append: yes
    groups: sudo
    createhome: no
- name: "Make user sudo with no-password"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{user}} ALL="
    line: "{{user}} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
    create: True
- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - unzip
    - tar
    - make
    - sed
    - curl
    - file
    - vim
    - wget
    - ntp
    - rsync
    - cron
    - htop
    - gcc
    - gettext
    - python-mysqldb # Needed to interact with mysql
    - python-passlib # To create password / htaccess
    - mosh # mobile shell https://mosh.mit.edu/#techinfo
    - apt-transport-https
- name: Ensure apache is present before uninstalling it
  apt:
    pkg: apache2
    state: present
- name: Stop apache if running
  service:
    name: apache2
    state: stopped
    enabled: False
- name: Ensure rookie packages are not here
  apt:
    pkg: "{{ item }}"
    state: absent
    purge: True
    force: True
  with_items:
   - apache2
   - apache2.2
   - apache2-utils
   - php
- name: To be sure that apache is gone
  shell: "apt-get -y autoremove && update-rc.d -f apache2 remove"
  become: true
  become_user: root
