---

## 
## Install monitoring server configuration
##
- name: Install the monitoring config
  hosts: monitoring-servers
  remote_user: "{{user}}"
  become: true
  become_user: root

  roles:
    - git
    - nginx
    - kibana

## 
## Install webserver configuration
##
- name: Install the base config for serving content
  hosts: front-servers
  remote_user: "{{user}}"
  become: true
  become_user: root

  roles:
    - nginx
    - git
    - supervisor
    - php-fpm
    - node

# Other available roles :
#   - mongo
#   - hhvm

  tasks:
    - name: Ensure the web folder is here
      file:
        path: "/home/{{user}}/www"
        state: directory
        group: www-data
        owner: "{{user}}"

## 
## Install broker configuration
##
- name: Install the base config for brokering
  hosts: broker-servers
  remote_user: "{{user}}"
  become: true
  become_user: root

  roles:
    - mosquitto
